/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 27.03.2026 11:35:48

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 10128;
#else
constexpr int kTensorArenaSize = 9104;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,3960 } };
const TfArray<1, float> quant0_scale = { 1, { 0.00390625, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 99, 40, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 99, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 50, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 50, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 400, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data6[3] = { 80, 245, -346, };
const TfArray<1, int> tensor_dimension6 = { 1, { 3 } };
const TfArray<1, float> quant6_scale = { 1, { 0.00010882411879720166, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[3*400] = { 
  13, 43, 20, -28, 4, 18, 6, -1, -4, 23, 13, -2, 5, 7, 23, -71, -4, 22, 7, -38, 14, 26, 20, 15, -3, 5, 24, -8, -5, -13, 7, -79, 4, 34, -4, -47, 18, -9, -8, 20, -13, -1, 22, 10, 6, -8, 9, -66, 6, 20, -2, -57, 9, -4, -2, 17, 7, 0, 16, -13, -4, 11, -13, -50, 9, 57, 5, -26, 33, 19, 11, 9, -4, 18, 10, 15, 8, 3, 15, -68, 1, 15, 21, -52, 24, 2, 12, 11, -9, 23, 19, 1, 8, 28, 26, -25, 1, 16, 12, -42, 12, 20, 7, 15, 4, -8, 26, 5, 2, 10, -3, -37, 9, 43, -1, -38, 29, 3, -15, 23, 8, 2, 2, -8, -1, 3, 15, -49, 15, 29, -3, -18, 10, -11, -6, -2, 1, -11, 6, 7, -7, 0, -3, -53, 1, 5, -4, -27, -3, -8, 18, -11, -6, -7, 2, 2, 9, -11, -4, -42, 19, 34, 0, -11, 20, 15, -7, -1, 9, 8, 17, 8, 28, -3, 15, -51, -7, 35, 26, -17, 42, 12, -2, 12, 8, 22, 31, 4, -3, 16, 8, -56, 16, 47, -9, 5, 31, 6, -7, 33, -4, 20, 30, 1, 13, -1, 4, -73, -1, -8, 6, 6, 14, -9, -23, 14, 19, 9, 1, 3, -5, 16, -2, -78, -13, 21, -5, -22, 17, 1, -12, 0, 9, 18, 15, 4, -2, 3, -11, -61, 2, 40, -7, -38, 14, -10, -13, 13, 3, -5, -18, 18, 18, 15, -2, -26, 4, 25, 22, -26, 2, -8, 0, 3, -9, 8, 32, 12, 8, -26, 2, -25, -8, 0, 16, -37, -3, -13, 13, -7, -2, -4, -25, -9, -1, 14, -11, -22, -13, 24, 18, -42, -10, -8, 8, 8, 8, -13, 2, -1, 10, 11, 10, -17, -10, 40, 8, -41, 5, 27, 6, 17, 11, 20, 6, -8, 16, -7, 0, -33, 17, 4, 4, -7, 1, 7, -11, 24, -2, 2, 12, -12, 8, -15, 2, -45, -12, 7, 1, -26, -2, -9, -2, 8, 14, -8, -15, 11, 13, 1, 14, -39, -7, 15, 11, -60, 26, 7, 15, 6, 11, -8, 25, 7, 1, -1, -3, -35, -4, 49, 24, -45, 24, 24, 3, 18, 18, 17, 8, 18, 7, 49, 6, -65, -9, 15, -7, -42, -1, 0, -2, -1, 2, 13, -18, -6, 3, 15, 12, -51, 
  6, 12, -70, 42, -15, -7, -16, -22, -25, -3, 2, 4, -4, -44, -36, -82, 6, 31, -84, 73, -4, -13, -29, -9, -15, -9, 15, 10, -15, -3, 3, -54, 9, 13, -53, 48, 12, -39, -37, 1, -7, -23, -10, -13, -19, -9, -5, -73, -2, 11, -79, 41, 0, -10, -43, -17, -19, -21, 1, -9, 5, -2, -33, -118, 6, 9, -66, 51, -12, -20, -23, -2, -23, -1, -16, 11, -23, -11, -31, -108, -13, 3, -83, 53, 8, -5, -41, 12, -11, 3, -11, 5, -10, -21, -32, -109, -15, 55, -59, 48, -2, 11, -68, 6, -18, 2, -13, -2, 12, -3, -8, -115, -17, 19, -23, 39, -2, 4, -19, 5, -11, 3, 26, -20, -4, 6, -21, -75, -18, 14, -59, 35, 15, 1, -23, -1, -27, -3, 15, -3, 24, 4, 9, -23, -16, 0, -19, 22, 8, -4, -10, -5, -11, 3, -13, -3, 4, 18, 19, 27, -3, 9, -54, 17, 4, -18, -21, -14, -18, -10, -13, 6, -14, -14, -27, -74, 6, 4, -37, 45, 7, -20, -15, -1, -8, 1, 6, -20, -33, -32, -2, -43, -7, 33, -42, 16, 28, 4, -18, 22, -9, 16, -18, 5, -6, 26, 29, -46, 10, 4, -75, 24, 30, -10, -42, -1, -15, 22, 43, 0, -10, -25, -24, 5, -14, 39, -29, 43, -6, 4, -5, 4, 12, 12, -25, 6, 25, 20, 25, -25, -6, 1, -35, 43, -2, -13, 8, -3, -20, -13, 40, 12, -4, -11, -15, -76, 7, 36, -93, 40, -20, 1, -49, 4, -6, 5, -29, 8, -7, 19, -6, -94, -6, 10, -69, 39, -2, -11, -41, -23, -12, -5, 19, -5, 3, -7, -10, -116, 3, 13, -84, 33, 5, -13, -49, 3, -17, -12, 45, -15, -20, -27, -28, -89, -2, 17, -69, 42, 5, -22, -31, -3, -21, 0, -17, 5, -21, 11, -23, -98, 0, 28, -46, 55, 21, -7, -8, -2, -10, 3, -12, -12, -21, -17, -17, -37, -2, 27, -50, 36, -17, -6, -18, 19, -17, -8, 9, 6, -23, -10, -13, -58, -7, 15, -55, 33, 11, 1, -54, -4, -30, -4, -12, -13, 0, -11, -9, -45, -14, 21, -79, 46, 9, -12, -80, -24, -15, -5, -11, -5, -37, -32, -28, -97, -6, 49, -39, 66, 11, -19, -46, -11, -8, -1, 21, -16, -2, -29, 4, -127, 
  -17, -79, 31, -37, -35, -24, 6, -20, 10, -15, 1, -18, -3, 14, -2, 111, 0, -101, 19, 11, -26, 2, 16, -29, -23, -7, -16, 7, 2, -3, 6, 82, -14, -65, 13, 9, -13, 9, 11, 2, 9, -18, -24, 9, 21, 2, -3, 71, -2, -57, 9, 25, -10, -17, 8, -3, 5, 2, -9, 5, 7, -12, 17, 77, 9, -79, 14, 23, -51, -13, -3, -21, -17, -25, -40, -3, 3, 30, -7, 94, -13, -55, 34, 10, -31, -20, 0, -21, 7, 0, -47, -8, -3, 8, -9, 56, -13, -113, 18, 64, -60, -4, 7, -23, 26, -20, -56, -9, -20, -4, 5, 95, -16, -98, 25, 3, -42, 13, 33, -28, 20, -28, -21, -16, -27, -17, -7, 42, 3, -62, 6, 21, -12, -15, 23, -19, 12, -10, -25, 0, 13, -10, 3, 46, -9, 6, 16, 76, 8, 9, 15, -15, -3, 4, 9, -8, -19, -28, -4, 26, 5, -70, 3, 49, -45, 0, 24, -1, 2, -16, -36, -3, -18, -4, 7, 84, 5, -99, 7, 20, -79, -25, 12, -12, -16, -24, -49, 5, 8, 12, 7, 78, 11, -111, 21, -2, -43, -4, 34, -25, 10, -24, -15, -5, -2, -38, -16, 91, -14, -32, 20, -9, -46, 10, 24, -35, 7, -24, -47, -3, 24, 2, 21, 89, -7, -67, 28, 21, -25, -8, 18, -30, 21, -31, 5, 13, -19, -21, -26, 78, -4, -33, -13, 38, 5, 5, 7, -1, 12, 14, -1, 4, 5, -8, -9, 65, -14, -95, 17, 23, -15, -5, 10, 10, -8, 10, -37, 1, -6, -11, 3, 53, -5, -10, 11, 12, 1, 2, 3, -17, -15, -7, 9, -9, -2, -10, -7, 74, -9, -44, 5, 8, -40, -22, 1, 11, -4, -13, -43, -21, -15, 27, 1, 67, 8, -105, 10, 25, -51, -10, 11, -9, 3, -14, -29, -12, -22, 1, 12, 72, -4, -40, 14, -35, -11, -2, 4, -5, 13, -2, -28, -15, 20, 18, 11, 73, 8, -41, 1, 11, -1, 7, 17, 5, -9, -10, 7, -8, 11, -10, 11, 63, 4, -54, 5, 58, -17, -3, 13, 1, -21, -6, -31, -8, 9, 7, -2, 60, 8, -97, 19, 50, -47, -3, 14, 8, -7, -9, -39, 11, -24, -16, 4, 103, -18, -70, 16, 3, -52, -25, 7, -28, -14, -10, -10, -4, 15, -21, -12, 113, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 3,400 } };
const TfArray<1, float> quant7_scale = { 1, { 0.0072016888298094273, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[16] = { -5489, -119, 5725, -4101, 169, 1754, 2416, 87, 1583, -15, 87, -2920, 2987, 1093, 1220, 4270, };
const TfArray<1, int> tensor_dimension8 = { 1, { 16 } };
const TfArray<16, float> quant8_scale = { 16, { 1.6774334653746337e-05, 4.8557089030509815e-05, 4.375409844215028e-05, 4.3545882363105193e-05, 4.5615077397087589e-05, 5.2925384807167575e-05, 7.4660471000242978e-05, 4.3214095057919621e-05, 5.5239117500605062e-05, 5.6718527048360556e-05, 2.8205786293256097e-05, 2.0288704035920091e-05, 3.8736656279070303e-05, 6.3637446146458387e-05, 6.8587709392886609e-05, 7.4047951784450561e-05, } };
const TfArray<16, int> quant8_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[16*1*3*8] = { 
  /* [0][0][][] */ 26,29,18,66,-73,-33,10,39, -24,4,-44,-42,-26,-7,79,-123, 16,39,-14,14,-127,-80,67,7, 
  /* [1][0][][] */ 23,-25,-1,-6,-14,-76,-2,15, -34,-100,0,-23,2,127,28,37, 30,-31,0,-62,-16,-44,1,-2, 
  /* [2][0][][] */ 17,21,11,1,-23,-44,-1,15, 127,-11,85,24,-29,-47,4,36, 20,10,51,-32,-33,-33,31,-8, 
  /* [3][0][][] */ -29,18,-34,5,127,4,-43,36, -127,9,-77,53,73,-3,-28,27, -110,22,-70,10,102,22,25,33, 
  /* [4][0][][] */ 101,-43,-8,-41,-28,-35,10,15, 67,-31,-5,-47,-22,51,11,-15, 127,10,21,-35,-19,74,-9,5, 
  /* [5][0][][] */ 127,-8,15,12,-18,-42,-14,30, 47,-8,-7,-33,-10,43,-32,-17, 14,14,18,5,-25,-10,-28,18, 
  /* [6][0][][] */ 127,2,17,13,-5,-21,8,0, 117,-15,22,-26,-14,-22,3,10, 63,-17,-16,17,-9,-19,-17,-23, 
  /* [7][0][][] */ 104,28,-11,-50,-127,62,36,24, 116,26,41,36,-63,43,14,30, 85,-8,-28,-13,-44,5,38,18, 
  /* [8][0][][] */ 127,-37,30,15,-4,-20,30,14, 103,-29,-55,12,-9,-17,-34,27, 109,-22,54,8,-13,-1,-11,-13, 
  /* [9][0][][] */ 127,-49,30,10,-16,29,22,14, 42,-42,-1,-35,-46,28,-14,8, 19,-47,3,16,-25,25,-12,25, 
  /* [10][0][][] */ -23,-53,-1,-10,-16,-24,27,-5, -73,-84,1,-58,-18,-63,-54,25, -83,-39,0,2,-22,127,-29,65, 
  /* [11][0][][] */ -74,23,-83,72,-7,0,-53,-73, -55,-80,-9,0,18,-111,-5,23, -36,-34,-107,50,-127,-100,-64,-39, 
  /* [12][0][][] */ 127,17,-25,43,-29,-11,34,-4, 114,-16,-41,-28,-32,39,-40,-13, 70,20,64,7,-10,-46,-30,31, 
  /* [13][0][][] */ 127,-21,-10,-26,-24,33,-13,-17, 102,2,-12,-15,-23,-24,-19,-27, 122,-1,27,-12,-7,-14,-23,6, 
  /* [14][0][][] */ 127,0,4,-11,-11,22,1,-15, 79,20,28,6,-20,1,19,-16, 49,-33,0,28,-23,-18,2,-20, 
  /* [15][0][][] */ 18,67,-17,45,-116,-71,-14,15, 2,33,18,37,-102,-91,1,11, -39,16,7,77,-127,-85,7,11, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 16,1,3,8 } };
const TfArray<16, float> quant9_scale = { 16, { 0.0024372281040996313, 0.0070551056414842606, 0.0063572549261152744, 0.0063270018436014652, 0.0066276458092033863, 0.0076897973194718361, 0.010847798548638821, 0.0062787951901555061, 0.0080259712412953377, 0.0082409223541617393, 0.0040981615893542767, 0.0029478487558662891, 0.0056282449513673782, 0.0092462068423628807, 0.0099654560908675194, 0.01075880229473114, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[8] = { -768, 17599, -4625, 29903, 7001, 22089, -6386, -772, };
const TfArray<1, int> tensor_dimension10 = { 1, { 8 } };
const TfArray<8, float> quant10_scale = { 8, { 3.4825676266336814e-05, 1.0306452168151736e-05, 1.5203107977868058e-05, 8.4917028289055452e-06, 1.4442467545450199e-05, 2.1252461010590196e-05, 7.8926705100457184e-06, 7.0058908931969199e-06, } };
const TfArray<8, int> quant10_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[8*1*3*40] = { 
  /* [0][0][][] */ -68,29,13,3,10,27,21,-4,-9,-2,-10,-13,27,-31,-45,-10,-25,-16,-23,-50,-14,-18,0,2,21,12,-3,-35,-25,-53,-68,-32,-40,-44,-3,-26,-31,-46,-61,-51, -41,55,16,35,64,29,31,26,-4,-3,8,35,-11,15,-3,8,2,-8,-15,-8,-37,6,-2,-13,-1,4,15,-13,-16,-39,-50,-20,-57,-44,9,9,-11,-28,-78,-55, -45,29,71,26,127,61,10,41,-17,6,-31,-2,42,-17,-29,-11,-40,-35,-9,-53,-24,-27,-32,-19,4,7,-27,26,-33,-56,-78,-65,-59,-45,-2,-4,-43,-44,-64,-73, 
  /* [1][0][][] */ -94,-49,-76,18,-127,33,-61,119,50,24,-30,-70,29,-60,76,14,-44,-1,66,54,16,-74,12,5,-12,-85,-88,-54,-71,-19,-19,-107,-53,8,-7,21,-68,-72,-12,-64, 61,-4,-104,-2,-61,49,69,119,38,-2,-20,-33,12,-59,-57,57,49,-18,-49,-43,23,44,-59,-42,-109,-51,-20,-66,-48,30,-43,-27,-27,52,-20,-35,-50,-26,-18,-84, 61,-51,-26,-72,-113,18,63,52,-24,47,-61,34,51,-43,-5,3,16,95,59,-42,-51,-14,-94,5,1,35,-66,49,-62,-94,16,-61,-3,-101,-64,31,32,-5,-59,34, 
  /* [2][0][][] */ 42,-40,-101,-2,-24,7,81,106,2,7,34,-7,49,-24,-22,22,16,8,30,-10,22,-66,18,14,46,-31,-45,-23,7,-38,-70,10,-60,2,38,-20,9,-94,-69,-86, 62,-82,-35,-12,65,65,68,22,118,-57,76,-7,5,37,63,17,-59,25,35,7,-18,-25,8,2,2,64,-25,29,-29,-33,-63,37,-64,-11,-17,-8,-44,-5,-89,-84, 50,-108,-81,-10,88,35,102,127,96,-59,-16,19,43,51,28,29,-46,10,48,-70,12,-43,-10,24,76,-29,2,7,24,43,-14,-16,-12,-70,29,-7,3,13,-76,-94, 
  /* [3][0][][] */ -22,-9,-47,-106,26,-97,33,1,55,-119,-48,-115,-65,-13,-13,-45,108,59,15,-23,5,11,48,63,-3,42,58,-97,51,0,25,35,42,17,23,15,-58,-18,-100,62, -75,-38,-41,-83,-1,-12,37,-49,70,15,-108,-69,-81,-98,37,-108,98,107,-31,-2,13,-27,-28,66,-39,-101,38,-82,-16,-70,51,72,11,-36,-75,-69,-31,-82,71,-46, 106,-8,31,-113,12,10,-13,17,-99,-16,52,-99,-125,-3,-114,-14,40,25,-61,42,-127,-16,-80,3,-79,-40,59,3,50,-101,66,-68,-17,-22,-75,-23,3,-101,-87,-32, 
  /* [4][0][][] */ -64,13,-50,-7,75,-22,-38,65,23,-90,-90,-49,92,77,27,17,42,-110,-5,26,-69,36,-54,-11,5,-22,89,44,55,-34,-37,-21,-69,-25,-4,-103,-48,81,18,40, -37,86,42,-80,41,-32,-4,-7,65,-96,-50,-32,65,87,3,-39,26,-64,53,17,-59,111,10,19,23,27,95,-5,15,22,-65,1,-96,-62,5,-39,-58,42,-22,18, -39,-2,-42,-37,50,18,-16,66,28,-127,-44,-35,98,93,-13,-20,9,-119,31,57,-23,92,-32,-53,43,-58,52,10,4,15,16,-98,0,6,-76,-27,11,75,21,-35, 
  /* [5][0][][] */ -71,14,-53,71,36,26,-11,15,2,7,-50,21,18,24,-2,-14,-33,-5,-12,6,-58,0,55,-58,29,-35,1,-9,-34,37,-18,18,17,13,20,3,2,-21,43,9, -99,-38,23,120,64,5,-2,4,19,-69,-55,-38,21,24,-4,-25,-5,-32,21,8,-24,-11,33,-7,-1,5,-38,-6,-5,9,-5,-29,-20,37,-34,-14,16,29,1,-6, 127,-127,-8,25,-15,24,-7,-61,36,28,-4,1,6,26,-18,-5,29,-39,1,-44,-18,39,-1,-11,20,-20,18,-4,-3,-10,24,11,0,-11,-28,-29,10,-23,32,62, 
  /* [6][0][][] */ 22,81,2,34,-24,-26,-48,-66,-96,-93,-57,12,-41,-31,9,-31,-44,86,6,-11,-36,49,-4,32,-34,-2,100,16,30,-40,-2,-82,53,-80,-75,34,-103,64,-59,-56, -66,-88,53,-9,-76,95,55,34,15,29,-50,74,-105,39,80,-52,-59,-84,68,69,-50,-103,-35,-26,-95,99,-19,42,-39,-37,71,74,-84,60,-79,55,89,56,-94,-54, -28,-64,-90,-41,-102,-87,-17,-43,74,72,-103,-91,-23,-88,-91,-94,60,-87,7,-56,-28,-127,36,-14,11,-14,-95,-28,-47,30,-66,-28,-34,62,-28,81,-51,-100,-117,-1, 
  /* [7][0][][] */ 79,-18,40,20,66,14,-102,45,-54,-73,79,-123,47,-120,-56,12,-37,86,-60,-33,-52,24,-116,-40,72,-26,-2,94,107,87,-48,-74,56,88,-15,-86,40,-38,39,-59, -39,0,-73,-58,-114,-95,21,51,-15,13,74,-121,27,-43,-122,-79,-111,-61,-12,-107,-41,9,34,29,-3,-35,-48,70,56,-52,-116,-34,58,29,76,11,16,33,-36,4, 22,-59,-69,-64,-89,-59,-27,-6,-45,21,-38,-18,-127,10,5,58,9,57,44,-33,-36,48,44,63,-85,110,35,90,-17,59,32,67,-101,-50,-106,10,-115,-85,39,18, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 8,1,3,40 } };
const TfArray<8, float> quant11_scale = { 8, { 0.0089153731241822243, 0.0026384517550468445, 0.0038919956423342228, 0.0021738759241998196, 0.003697271691635251, 0.0054406300187110901, 0.0020205236505717039, 0.0017935080686584115, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,99,40 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,1,99,8 } };
const TfArray<1, float> quant13_scale = { 1, { 0.0068825460039079189, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,99,1,8 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,50,1,8 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,50,8 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,50,16 } };
const TfArray<1, float> quant17_scale = { 1, { 0.015110916458070278, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,50,1,16 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,25,1,16 } };
const TfArray<2, int> tensor_dimension20 = { 2, { 1,400 } };
const TfArray<2, int> tensor_dimension21 = { 2, { 1,3 } };
const TfArray<1, float> quant21_scale = { 1, { 0.27654373645782471, } };
const TfArray<1, int> quant21_zero = { 1, { 54 } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&quant21_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 12 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 12,11,10 } };
const TfArray<1, int> outputs1 = { 1, { 13 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 13,2 } };
const TfArray<1, int> outputs2 = { 1, { 14 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 14 } };
const TfArray<1, int> outputs3 = { 1, { 15 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 15,3 } };
const TfArray<1, int> outputs4 = { 1, { 16 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 16,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 17 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 17,4 } };
const TfArray<1, int> outputs6 = { 1, { 18 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 18 } };
const TfArray<1, int> outputs7 = { 1, { 19 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 19,5 } };
const TfArray<1, int> outputs8 = { 1, { 20 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 20,7,6 } };
const TfArray<1, int> outputs9 = { 1, { 21 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 21 } };
const TfArray<1, int> outputs10 = { 1, { 22 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3968), (TfLiteIntArray*)&g0::tensor_dimension0, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 1200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3968), (TfLiteIntArray*)&g0::tensor_dimension13, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension15, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension17, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension19, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension21, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 23, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  22, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_927857_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 23;
  for (size_t i = 0; i < 23; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_927857_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_927857_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_927857_3_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_927857_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
