import pathlib


REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
MAIN_DIR = REPO_ROOT / "main"
MAIN_CMAKE = MAIN_DIR / "CMakeLists.txt"

APP_DIR = MAIN_DIR / "app"
SERVICES_DIR = MAIN_DIR / "services"
FEATURES_DIR = MAIN_DIR / "features"
UI_DIR = MAIN_DIR / "ui"
UI_CUSTOM_DIR = UI_DIR / "custom"
UI_GENERATED_DIR = UI_DIR / "generated"

ALERTS_DIR = FEATURES_DIR / "alerts"
DANGER_DETECTION_DIR = FEATURES_DIR / "danger_detection"
AUDIO_DIR = FEATURES_DIR / "audio"
WEATHER_DIR = FEATURES_DIR / "weather"
MINI_GAMES_DIR = FEATURES_DIR / "mini_games"

APP_MAIN_SOURCE = APP_DIR / "app_main.c"
HARDWARE_INIT_SOURCE = APP_DIR / "hardware_init.c"
HARDWARE_INIT_HEADER = APP_DIR / "hardware_init.h"
BOARD_IMU_SOURCE = APP_DIR / "board_imu.c"
BOARD_IMU_HEADER = APP_DIR / "board_imu.h"

NETWORK_SERVICE_SOURCE = SERVICES_DIR / "network_service.c"
NETWORK_SERVICE_HEADER = SERVICES_DIR / "network_service.h"
OFFICIAL_CHAT_SERVICE_SOURCE = SERVICES_DIR / "official_chat_service.c"
OFFICIAL_CHAT_SERVICE_HEADER = SERVICES_DIR / "official_chat_service.h"
MEMORY_WATCH_SERVICE_SOURCE = SERVICES_DIR / "memory_watch_service.c"
MEMORY_WATCH_SERVICE_HEADER = SERVICES_DIR / "memory_watch_service.h"
MEMORY_WATCH_OGG_OPUS_MUXER_SOURCE = SERVICES_DIR / "memory_watch_ogg_opus_muxer.c"
MEMORY_WATCH_OGG_OPUS_MUXER_HEADER = SERVICES_DIR / "memory_watch_ogg_opus_muxer.h"
MEMORY_WATCH_RECORDER_SOURCE = SERVICES_DIR / "memory_watch_recorder.c"
MEMORY_WATCH_RECORDER_HEADER = SERVICES_DIR / "memory_watch_recorder.h"
MEMORY_WATCH_VOICE_CLIENT_SOURCE = SERVICES_DIR / "memory_watch_voice_client.c"
MEMORY_WATCH_VOICE_CLIENT_HEADER = SERVICES_DIR / "memory_watch_voice_client.h"
SYSTEM_TIME_SERVICE_SOURCE = SERVICES_DIR / "system_time_service.c"
SYSTEM_TIME_SERVICE_HEADER = SERVICES_DIR / "system_time_service.h"
IMU_SERVICE_SOURCE = SERVICES_DIR / "imu_service.c"
IMU_SERVICE_HEADER = SERVICES_DIR / "imu_service.h"

WIFI_CONTROL_DIR = REPO_ROOT / "components" / "wifi_control"
WIFI_CONTROL_INCLUDE_DIR = WIFI_CONTROL_DIR / "include"
WIFI_CONTROL_SRC_DIR = WIFI_CONTROL_DIR / "src"
WIFI_CONTROL_HEADER = WIFI_CONTROL_INCLUDE_DIR / "wifi_control.h"
WIFI_CONTROL_INTERNAL_HEADER = WIFI_CONTROL_SRC_DIR / "wifi_control_internal.h"
WIFI_CONTROL_SOURCE = WIFI_CONTROL_SRC_DIR / "wifi_control.c"

NETWORK_CREDENTIALS_DIR = REPO_ROOT / "components" / "network_credentials"
NETWORK_CREDENTIALS_INCLUDE_DIR = NETWORK_CREDENTIALS_DIR / "include"
NETWORK_CREDENTIALS_SRC_DIR = NETWORK_CREDENTIALS_DIR / "src"
NETWORK_CREDENTIALS_HEADER = (
    NETWORK_CREDENTIALS_INCLUDE_DIR / "network_credentials.h"
)
NETWORK_CREDENTIALS_SOURCE = NETWORK_CREDENTIALS_SRC_DIR / "network_credentials.c"

BLE_CONTROL_DIR = REPO_ROOT / "components" / "ble_control"
BLE_CONTROL_INCLUDE_DIR = BLE_CONTROL_DIR / "include"
BLE_CONTROL_SRC_DIR = BLE_CONTROL_DIR / "src"
BLE_CONTROL_HEADER = BLE_CONTROL_INCLUDE_DIR / "ble_control.h"
BLE_CONTROL_SOURCE = BLE_CONTROL_SRC_DIR / "ble_control.c"

BLE_PRESENCE_DIR = REPO_ROOT / "components" / "ble_presence"
BLE_PRESENCE_INCLUDE_DIR = BLE_PRESENCE_DIR / "include"
BLE_PRESENCE_SRC_DIR = BLE_PRESENCE_DIR / "src"
BLE_PRESENCE_HEADER = BLE_PRESENCE_INCLUDE_DIR / "ble_presence.h"
BLE_PRESENCE_SOURCE = BLE_PRESENCE_SRC_DIR / "ble_presence.c"

NETWORK_MANAGER_DIR = REPO_ROOT / "components" / "network_manager"
NETWORK_MANAGER_INCLUDE_DIR = NETWORK_MANAGER_DIR / "include"
NETWORK_MANAGER_SRC_DIR = NETWORK_MANAGER_DIR / "src"
NETWORK_MANAGER_HEADER = NETWORK_MANAGER_INCLUDE_DIR / "network_manager.h"
NETWORK_MANAGER_SOURCE = NETWORK_MANAGER_SRC_DIR / "network_manager.c"

NETWORK_PROVISIONING_ADAPTER_DIR = (
    REPO_ROOT / "components" / "network_provisioning_adapter"
)
NETWORK_PROVISIONING_ADAPTER_INCLUDE_DIR = (
    NETWORK_PROVISIONING_ADAPTER_DIR / "include"
)
NETWORK_PROVISIONING_ADAPTER_SRC_DIR = NETWORK_PROVISIONING_ADAPTER_DIR / "src"
NETWORK_PROVISIONING_ADAPTER_HEADER = (
    NETWORK_PROVISIONING_ADAPTER_INCLUDE_DIR / "network_provisioning_adapter.h"
)
NETWORK_PROVISIONING_ADAPTER_SOURCE = (
    NETWORK_PROVISIONING_ADAPTER_SRC_DIR / "network_provisioning_adapter.c"
)

AP_PORTAL_ADAPTER_DIR = REPO_ROOT / "components" / "ap_portal_adapter"
AP_PORTAL_ADAPTER_INCLUDE_DIR = AP_PORTAL_ADAPTER_DIR / "include"
AP_PORTAL_ADAPTER_SRC_DIR = AP_PORTAL_ADAPTER_DIR / "src"
AP_PORTAL_ADAPTER_HEADER = AP_PORTAL_ADAPTER_INCLUDE_DIR / "ap_portal_adapter.h"
AP_PORTAL_ADAPTER_SOURCE = AP_PORTAL_ADAPTER_SRC_DIR / "ap_portal_adapter.c"
AP_PORTAL_ROUTES_HEADER = AP_PORTAL_ADAPTER_SRC_DIR / "ap_portal_routes.h"
AP_PORTAL_ROUTES_SOURCE = AP_PORTAL_ADAPTER_SRC_DIR / "ap_portal_routes.c"
AP_PORTAL_WEB_DIR = AP_PORTAL_ADAPTER_DIR / "web"
AP_PORTAL_WEB_INDEX = AP_PORTAL_WEB_DIR / "index.html"
AP_PORTAL_WEB_JS = AP_PORTAL_WEB_DIR / "app.js"
AP_PORTAL_WEB_PROV_CLIENT = AP_PORTAL_WEB_DIR / "prov_client.js"
AP_PORTAL_WEB_PROTO_BUNDLE = AP_PORTAL_WEB_DIR / "prov_proto_bundle.js"
AP_PORTAL_WEB_CSS = AP_PORTAL_WEB_DIR / "app.css"

CAPTIVE_PORTAL_DNS_DIR = REPO_ROOT / "components" / "captive_portal_dns"
CAPTIVE_PORTAL_DNS_INCLUDE_DIR = CAPTIVE_PORTAL_DNS_DIR / "include"
CAPTIVE_PORTAL_DNS_SRC_DIR = CAPTIVE_PORTAL_DNS_DIR / "src"
CAPTIVE_PORTAL_DNS_HEADER = CAPTIVE_PORTAL_DNS_INCLUDE_DIR / "captive_portal_dns.h"
CAPTIVE_PORTAL_DNS_SOURCE = CAPTIVE_PORTAL_DNS_SRC_DIR / "captive_portal_dns.c"

APP_ALERT_MANAGER_SOURCE = ALERTS_DIR / "app_alert_manager.c"
APP_ALERT_MANAGER_HEADER = ALERTS_DIR / "app_alert_manager.h"
AUDIO_ALERT_PLAYER_SOURCE = ALERTS_DIR / "audio_alert_player.c"
AUDIO_ALERT_PLAYER_HEADER = ALERTS_DIR / "audio_alert_player.h"
DISPLAY_ALERT_ADAPTER_SOURCE = ALERTS_DIR / "display_alert_adapter.c"
DISPLAY_ALERT_ADAPTER_HEADER = ALERTS_DIR / "display_alert_adapter.h"

DANGER_DETECTION_SERVICE_SOURCE = (
    DANGER_DETECTION_DIR / "danger_detection_service.c"
)
DANGER_DETECTION_SERVICE_HEADER = (
    DANGER_DETECTION_DIR / "danger_detection_service.h"
)

AUDIO_APP_SOURCE = AUDIO_DIR / "audio_app.c"
AUDIO_APP_HEADER = AUDIO_DIR / "audio_app.h"

TIME_WEATHER_SOURCE = WEATHER_DIR / "time_weather.c"
TIME_WEATHER_HEADER = WEATHER_DIR / "time_weather.h"
HPTTS_SOURCE = WEATHER_DIR / "hptts.c"
HPTTS_HEADER = WEATHER_DIR / "hptts.h"

LVGL_TASK_SOURCE = UI_DIR / "lvgl_task.c"
LVGL_TASK_HEADER = UI_DIR / "lvgl_task.h"
UI_REFRESH_POLICY_SOURCE = UI_DIR / "ui_refresh_policy.c"
UI_REFRESH_POLICY_HEADER = UI_DIR / "ui_refresh_policy.h"
UI_CUSTOM_HEADER = UI_CUSTOM_DIR / "custom.h"
UI_MAIN_DROPDOWN_CONTROLLER_SOURCE = UI_CUSTOM_DIR / "main_dropdown_controller.c"
UI_MAIN_DROPDOWN_CONTROLLER_HEADER = UI_CUSTOM_DIR / "main_dropdown_controller.h"
UI_WIFI_MANAGEMENT_CONTROLLER_SOURCE = (
    UI_CUSTOM_DIR / "wifi_management_controller.c"
)
UI_WIFI_MANAGEMENT_CONTROLLER_HEADER = (
    UI_CUSTOM_DIR / "wifi_management_controller.h"
)
UI_MINI_GAMES_CONTROLLER_SOURCE = UI_CUSTOM_DIR / "mini_games_controller.c"
UI_MINI_GAMES_CONTROLLER_HEADER = UI_CUSTOM_DIR / "mini_games_controller.h"
UI_EVENTS_INIT_SOURCE = UI_GENERATED_DIR / "events_init.c"
UI_EVENTS_INIT_HEADER = UI_GENERATED_DIR / "events_init.h"

BOARD_POWER_SOURCE = APP_DIR / "board_power.c"
BOARD_POWER_HEADER = APP_DIR / "board_power.h"
BOARD_BUTTON_SOURCE = APP_DIR / "board_button.c"
BOARD_BUTTON_HEADER = APP_DIR / "board_button.h"
MINI_GAME_2048_SOURCE = MINI_GAMES_DIR / "mini_game_2048.c"
MINI_GAME_2048_HEADER = MINI_GAMES_DIR / "mini_game_2048.h"

POWER_SERVICE_SOURCE = SERVICES_DIR / "power_service.c"
POWER_SERVICE_HEADER = SERVICES_DIR / "power_service.h"
POWER_POLICY_SOURCE = SERVICES_DIR / "power_policy.c"
POWER_POLICY_HEADER = SERVICES_DIR / "power_policy.h"
SLEEP_COORDINATOR_SOURCE = SERVICES_DIR / "sleep_coordinator.c"
SLEEP_COORDINATOR_HEADER = SERVICES_DIR / "sleep_coordinator.h"
WAKEUP_EVIDENCE_SERVICE_SOURCE = SERVICES_DIR / "wakeup_evidence_service.c"
WAKEUP_EVIDENCE_SERVICE_HEADER = SERVICES_DIR / "wakeup_evidence_service.h"
STARTUP_READINESS_SOURCE = SERVICES_DIR / "startup_readiness.c"
STARTUP_READINESS_HEADER = SERVICES_DIR / "startup_readiness.h"
BACKGROUND_SERVICE_MANAGER_SOURCE = SERVICES_DIR / "background_service_manager.c"
BACKGROUND_SERVICE_MANAGER_HEADER = SERVICES_DIR / "background_service_manager.h"
SAFETY_MONITOR_SESSION_SOURCE = SERVICES_DIR / "safety_monitor_session.c"
SAFETY_MONITOR_SESSION_HEADER = SERVICES_DIR / "safety_monitor_session.h"

PCF85063ATL_DIR = REPO_ROOT / "components" / "pcf85063atl"
PCF85063ATL_HEADER = PCF85063ATL_DIR / "include" / "pcf85063atl.h"
PCF85063ATL_SOURCE = PCF85063ATL_DIR / "pcf85063atl.c"
PCF85063ATL_CMAKE = PCF85063ATL_DIR / "CMakeLists.txt"

QMI8658C_DIR = REPO_ROOT / "components" / "qmi8658c"
QMI8658C_HEADER = QMI8658C_DIR / "include" / "qmi8658c.h"
QMI8658C_SOURCE = QMI8658C_DIR / "qmi8658c.c"
QMI8658C_REGS_HEADER = QMI8658C_DIR / "qmi8658c_regs.h"
QMI8658C_CMAKE = QMI8658C_DIR / "CMakeLists.txt"

IMU_MOTION_DIR = REPO_ROOT / "components" / "imu_motion"
IMU_MOTION_HEADER = IMU_MOTION_DIR / "include" / "imu_motion.h"
IMU_MOTION_SOURCE = IMU_MOTION_DIR / "imu_motion.c"
IMU_MOTION_CMAKE = IMU_MOTION_DIR / "CMakeLists.txt"

IMU_RAISE_SAMPLE_SCRIPT = REPO_ROOT / "scripts" / "extract_imu_raise_samples.py"

SYSTEM_TIME_DIR = REPO_ROOT / "components" / "system_time"
SYSTEM_TIME_HEADER = SYSTEM_TIME_DIR / "include" / "system_time.h"
SYSTEM_TIME_SOURCE = SYSTEM_TIME_DIR / "system_time.c"
SYSTEM_TIME_CMAKE = SYSTEM_TIME_DIR / "CMakeLists.txt"

GET_TIME_DIR = REPO_ROOT / "components" / "get_time"

OFFICIAL_CHAT_DIR = REPO_ROOT / "components" / "official_chat"
OFFICIAL_CHAT_HEADER = OFFICIAL_CHAT_DIR / "include" / "official_chat.h"
OFFICIAL_CHAT_OTA_SOURCE = OFFICIAL_CHAT_DIR / "ota.cc"
OFFICIAL_CHAT_C_API_SOURCE = OFFICIAL_CHAT_DIR / "official_chat_c_api.cc"
