import pathlib
import unittest


REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
MAIN_CMAKELISTS = REPO_ROOT / "main" / "CMakeLists.txt"
SDKCONFIG = REPO_ROOT / "sdkconfig"
SDKCONFIG_DEFAULTS = REPO_ROOT / "sdkconfig.defaults"
CUSTOM_HEADER = REPO_ROOT / "main" / "ui" / "custom" / "custom.h"
CHINESE_FONT_HEADER = REPO_ROOT / "main" / "ui" / "custom" / "ui_chinese_fonts.h"
COMPILED_FONTS_DIR = REPO_ROOT / "main" / "ui" / "custom" / "fonts"


class UiChineseFontsSourceTests(unittest.TestCase):
    def test_main_component_compiles_chinese_font_sources(self) -> None:
        source = MAIN_CMAKELISTS.read_text(encoding="utf-8")

        self.assertIn("ui_custom_font_srcs", source)
        self.assertIn("ui/custom/fonts/*.c", source)
        self.assertNotIn("ui/custom/ui_runtime_fonts.c", source)

    def test_custom_header_exposes_chinese_font_symbols(self) -> None:
        source = CUSTOM_HEADER.read_text(encoding="utf-8")

        self.assertIn('#include "ui_chinese_fonts.h"', source)
        self.assertNotIn('#include "ui_runtime_fonts.h"', source)

    def test_header_declares_direct_font_symbols(self) -> None:
        source = CHINESE_FONT_HEADER.read_text(encoding="utf-8")

        self.assertIn("LV_FONT_DECLARE", source)
        self.assertIn("不要改用", source)
        self.assertIn("lv_font_montserrat_lxgw_", source)
        for size in (16, 22):
            self.assertIn(
                f"LV_FONT_DECLARE(lv_font_montserrat_lxgw_common_5500_{size}_4);",
                source,
            )
        self.assertIn(
            "LV_FONT_DECLARE(lv_font_montserrat_lxgw_tghz_static_27_4);",
            source,
        )

    def test_compiled_fonts_export_declared_symbols(self) -> None:
        for size in (16, 22):
            source = (
                COMPILED_FONTS_DIR
                / f"lv_font_montserrat_lxgw_common_5500_{size}_4.c"
            ).read_text(encoding="utf-8")

            self.assertIn(
                f"lv_font_montserrat_lxgw_common_5500_{size}_4",
                source,
            )
            self.assertIn("Generated by scripts/lvgl_fonts/build_lvgl_cfont.py", source)

        charset = (
            REPO_ROOT / "tools/lvgl_fonts/charsets/charset_tghz_common_5500.txt"
        ).read_text(encoding="utf-8")
        self.assertEqual(len({char for char in charset if not char.isspace()}), 5500)
        self.assertFalse(
            (COMPILED_FONTS_DIR / "lv_font_montserrat_lxgw_tghz_level1_3500_24_4.c").exists()
        )

        static_source = (
            COMPILED_FONTS_DIR / "lv_font_montserrat_lxgw_tghz_static_27_4.c"
        ).read_text(encoding="utf-8")
        self.assertIn("lv_font_montserrat_lxgw_tghz_static_27_4", static_source)
        self.assertIn("Generated by scripts/lvgl_fonts/build_lvgl_cfont.py", static_source)
        self.assertFalse(
            (COMPILED_FONTS_DIR / "lv_font_montserrat_lxgw_tghz_level1_3500_27_4.c").exists()
        )

    def test_compressed_font_runtime_is_enabled(self) -> None:
        compressed_font_sources = [
            path
            for path in COMPILED_FONTS_DIR.glob("*.c")
            if ".bitmap_format = 1" in path.read_text(encoding="utf-8")
        ]

        self.assertTrue(
            compressed_font_sources,
            "Chinese font sources should stay compressed unless regenerated.",
        )
        self.assertIn(
            "CONFIG_LV_USE_FONT_COMPRESSED=y",
            SDKCONFIG.read_text(encoding="utf-8"),
        )
        self.assertIn(
            "CONFIG_LV_USE_FONT_COMPRESSED=y",
            SDKCONFIG_DEFAULTS.read_text(encoding="utf-8"),
        )


if __name__ == "__main__":
    unittest.main()
