import pathlib
import unittest


REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
MAIN_CMAKELISTS = REPO_ROOT / "main" / "CMakeLists.txt"
CUSTOM_HEADER = REPO_ROOT / "main" / "ui" / "custom" / "custom.h"
CHINESE_FONT_HEADER = REPO_ROOT / "main" / "ui" / "custom" / "ui_chinese_fonts.h"
COMPILED_FONTS_DIR = REPO_ROOT / "main" / "ui" / "custom" / "fonts"


class UiChineseFontsSourceTests(unittest.TestCase):
    def test_main_component_compiles_chinese_font_sources(self) -> None:
        source = MAIN_CMAKELISTS.read_text(encoding="utf-8")

        self.assertIn("ui_custom_font_srcs", source)
        self.assertIn("ui/custom/fonts/*.c", source)
        self.assertNotIn("ui/custom/ui_runtime_fonts.c", source)

    def test_custom_header_exposes_chinese_font_symbols(self) -> None:
        source = CUSTOM_HEADER.read_text(encoding="utf-8")

        self.assertIn('#include "ui_chinese_fonts.h"', source)
        self.assertNotIn('#include "ui_runtime_fonts.h"', source)

    def test_header_declares_direct_font_symbols(self) -> None:
        source = CHINESE_FONT_HEADER.read_text(encoding="utf-8")

        self.assertIn("LV_FONT_DECLARE", source)
        self.assertIn("不要改用", source)
        self.assertIn("lv_font_montserrat*", source)
        for size in (16, 22, 24, 27):
            self.assertIn(
                f"LV_FONT_DECLARE(lv_font_montserrat_lxgw_tghz_level1_3500_{size}_4);",
                source,
            )

    def test_compiled_fonts_export_declared_symbols(self) -> None:
        for size in (16, 22, 24, 27):
            source = (
                COMPILED_FONTS_DIR
                / f"lv_font_montserrat_lxgw_tghz_level1_3500_{size}_4.c"
            ).read_text(encoding="utf-8")

            self.assertIn(
                f"lv_font_montserrat_lxgw_tghz_level1_3500_{size}_4",
                source,
            )
            self.assertIn("Generated by scripts/lvgl_fonts/build_lvgl_cfont.py", source)


if __name__ == "__main__":
    unittest.main()
