#pragma once

#define AUDIO_PLATFORM_HW_SAMPLE_RATE 24000
#define AUDIO_PLATFORM_HW_BITS_PER_SAMPLE 16
#define AUDIO_PLATFORM_HW_INPUT_CHANNELS 2
#define AUDIO_PLATFORM_HW_OUTPUT_CHANNELS 1

#define AUDIO_PLATFORM_SR_SAMPLE_RATE 16000
#define AUDIO_PLATFORM_SR_BITS_PER_SAMPLE 16

#define AUDIO_PLATFORM_ADC_CHANNEL_FORMAT "MR"
#define AUDIO_PLATFORM_CHAT_BUTTON_GPIO 0
