ARG HERMES_BASE_IMAGE=docker.1panel.live/nousresearch/hermes-agent:latest
FROM ${HERMES_BASE_IMAGE}

USER root
RUN /usr/local/bin/uv pip install \
        --python /opt/hermes/.venv/bin/python3 \
        --index-url https://mirrors.aliyun.com/pypi/simple \
        mem0ai==2.0.10
