FROM nousresearch/hermes-agent:latest

USER root
RUN /usr/local/bin/uv pip install \
        --python /opt/hermes/.venv/bin/python3 \
        --index-url https://mirrors.aliyun.com/pypi/simple \
        mem0ai==2.0.10
