#!/usr/bin/env python3
"""生成编译进固件的 LVGL C 格式中文字体。"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
from pathlib import Path

from build_lvgl_binfont import (
    ASCII_RANGE,
    DEFAULT_BPP,
    DEFAULT_CHARSET,
    DEFAULT_CHINESE_FONT,
    DEFAULT_LATIN_FONT,
    LV_FONT_CONV_PACKAGE,
    REPO_ROOT,
    read_charset,
)


DEFAULT_OUTPUT_DIR = REPO_ROOT / "main" / "ui" / "custom" / "fonts"


def default_output_name(size: int, charset_name: str, bpp: int) -> str:
    return f"lv_font_montserrat_lxgw_{charset_name}_{size}_{bpp}.c"


def sanitize_generated_header(path: Path, size: int, bpp: int) -> None:
    source = path.read_text(encoding="utf-8")
    source = re.sub(
        r"/\*{10,}.*?\*{10,}/",
        (
            "/*******************************************************************************\n"
            f" * LVGL compiled Chinese font: size={size}, bpp={bpp}\n"
            " * Generated by scripts/lvgl_fonts/build_lvgl_cfont.py.\n"
            " ******************************************************************************/"
        ),
        source,
        count=1,
        flags=re.S,
    )
    path.write_text(source, encoding="utf-8", newline="\n")


def build_font(args: argparse.Namespace) -> Path:
    latin_font = Path(args.latin_font)
    chinese_font = Path(args.chinese_font)
    charset = Path(args.charset)

    for path in (latin_font, chinese_font, charset):
        if not path.exists():
            raise FileNotFoundError(path)

    npx = shutil.which("npx") or shutil.which("npx.cmd")
    if npx is None:
        raise FileNotFoundError("npx or npx.cmd")

    output = Path(args.output) if args.output else Path(args.output_dir) / default_output_name(
        args.size,
        args.name,
        args.bpp,
    )
    output.parent.mkdir(parents=True, exist_ok=True)

    subprocess.run(
        [
            npx,
            "--yes",
            "--package",
            LV_FONT_CONV_PACKAGE,
            "lv_font_conv",
            "--font",
            str(latin_font),
            "--range",
            ASCII_RANGE,
            "--font",
            str(chinese_font),
            "--symbols",
            read_charset(charset),
            "--size",
            str(args.size),
            "--bpp",
            str(args.bpp),
            "--format",
            "lvgl",
            "--output",
            str(output),
        ],
        check=True,
    )
    sanitize_generated_header(output, args.size, args.bpp)
    return output


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="生成编译进固件的 LVGL C 字体")
    parser.add_argument("--size", type=int, required=True, help="字号，例如 24")
    parser.add_argument("--bpp", type=int, default=DEFAULT_BPP, help="位深，默认 4")
    parser.add_argument("--name", default="tghz_level1_3500", help="输出文件名中的字符集标签")
    parser.add_argument("--latin-font", default=DEFAULT_LATIN_FONT, help="拉丁字体 TTF")
    parser.add_argument("--chinese-font", default=DEFAULT_CHINESE_FONT, help="中文字体 TTF")
    parser.add_argument("--charset", default=DEFAULT_CHARSET, help="中文字符集文本")
    parser.add_argument("--output-dir", default=DEFAULT_OUTPUT_DIR, help="默认输出目录")
    parser.add_argument("--output", help="指定完整输出文件路径")
    return parser.parse_args()


def main() -> None:
    output = build_font(parse_args())
    print(f"generated: {output}")


if __name__ == "__main__":
    main()
